/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7531810c8d3a5cfc50fcb30b4b87b129)
interface __BaseEnv_Env {
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	TIKTOK_API_BASE_URL: "https://open-api.tiktokglobalshop.com";
	TIKTOK_ORDER_API_VERSION: "202309";
	TIKTOK_RETURNS_API_VERSION: "202602";
	TIKTOK_FINANCE_API_VERSION: "202501";
	SESSION_SECRET: string;
	PRIMARY_BOOTSTRAP_PASSWORD: string;
	RECOVERY_BOOTSTRAP_PASSWORD: string;
	AUTH_PASSWORD_VERSION: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TIKTOK_API_BASE_URL" | "TIKTOK_ORDER_API_VERSION" | "TIKTOK_RETURNS_API_VERSION" | "TIKTOK_FINANCE_API_VERSION" | "SESSION_SECRET" | "PRIMARY_BOOTSTRAP_PASSWORD" | "RECOVERY_BOOTSTRAP_PASSWORD" | "AUTH_PASSWORD_VERSION">> {}
}
