"use client";
import { useState } from "react";

const ADMIN="hazel.w@saphiant.com";
const nav=["经营总览","退货率分析","BBY 销售与 P&L","价格核验","数据与自动化","访问管理"];
const trend=[42,50,44,61,54,66,73,62,81,76,90,84];
const modules=[
  ["W","Walmart 退货率","订单 + 退货 Excel；品牌、SKU、月份、原因分析","手工上传","已读取"],
  ["B","Best Buy 退货率","订单 + 退货 + SKU 清洗；数据透视与 SAP 口径","手工上传","已读取"],
  ["$","Best Buy 销售 / P&L","销售与成本字段已可用；完整 P&L 仍需费用输入","手工上传","待补成本"],
  ["◇","三平台价格核验","Amazon / Walmart / Best Buy 搜索页实时抓取","网页抓取","非 API"],
];
type Allowed={email:string;role:string;createdAt:number};

export default function Dashboard({email,admin,initialAllowed}:{email:string;admin:boolean;initialAllowed:Allowed[]}){
  const [tab,setTab]=useState(0); const [items,setItems]=useState(initialAllowed); const [newEmail,setNewEmail]=useState("");
  async function update(method:"POST"|"DELETE",target:string){const password=method==="POST"?prompt("请为该邮箱设置至少 10 位临时密码：")||"":undefined;if(method==="POST"&&password.length<10){alert("临时密码至少需要 10 位");return}const res=await fetch("/api/access",{method,headers:{"content-type":"application/json"},body:JSON.stringify({email:target,password})});if(res.ok){const data=await res.json();setItems(data.items);setNewEmail("")}else alert((await res.json()).error||"操作失败")}
  return <main className="shell"><aside className="sidebar"><div className="side-brand"><span className="brand-mark">S</span><span>SAPHIANT<small>BI CONTROL ROOM</small></span></div><nav>{nav.map((n,i)=><button key={n} onClick={()=>setTab(i)} className={tab===i?"active":""}><b>{["⌁","↩","$","◇","↥","◎"][i]}</b>{n}</button>)}</nav><div className="side-user"><strong>{admin?"Hazel · Owner":"Authorized Viewer"}</strong><small>{email}</small></div></aside><section className="workspace"><header className="topbar"><div><p className="crumb">SAPHIANT / BI SYSTEM</p><h1>{nav[tab]}</h1></div><span className="live">安全访问已验证</span></header>{tab<5&&<div className="filters"><label>平台<select><option>全部平台</option><option>Walmart</option><option>Best Buy</option><option>Amazon</option></select></label><label>品牌<select><option>全部品牌</option><option>Dreame</option><option>Cudy</option><option>Yaber</option></select></label><label>时间范围<input defaultValue="2025-12 — 2026-05"/></label><button className="apply">应用筛选</button></div>}{tab===0&&<Overview setTab={setTab}/>} {tab>0&&tab<5&&<Analysis tab={tab}/>} {tab===5&&<section className="access"><div className="section-head"><div><p className="kicker">ACCESS CONTROL</p><h2>允许访问的邮箱</h2></div><span className="owner">最终管理员 · Hazel</span></div>{!admin?<div className="error-box">只有 {ADMIN} 可以管理访问权限。</div>:<><form className="invite" onSubmit={e=>{e.preventDefault();update("POST",newEmail)}}><label>允许新的邮箱访问<br/><small>添加后，请把临时密码安全地发给对方。</small></label><input type="email" required value={newEmail} onChange={e=>setNewEmail(e.target.value)} placeholder="colleague@saphiant.com"/><button>加入白名单</button></form><div className="allowlist"><div><span>邮箱</span><span>权限</span><span>状态</span><span/></div>{items.map(x=><div key={x.email}><span>{x.email}</span><span>{x.email===ADMIN?"超级管理员":"查看者"}</span><span className="state">● 已允许</span><button disabled={x.email===ADMIN} onClick={()=>update("DELETE",x.email)}>{x.email===ADMIN?"不可删除":"移除"}</button></div>)}</div></>}</section>}</section></main>
}

function Overview({setTab}:{setTab:(n:number)=>void}){return <><div className="notice"><b>i</b><span><strong>自动化现状：</strong>当前 BBY / WMT 数据均未接 API；页面先承接现有 Excel 流程，接口将在下一阶段接入。</span></div><div className="kpis"><article><p>WMT 累计 SKU</p><strong>124</strong><small>已生成趋势总览</small></article><article><p>WMT 数据记录</p><strong>3,898</strong><small>订单与退货合并结果</small></article><article><p>BBY 销售订单</p><strong>2,034</strong><small>P&amp;L 待补费用口径</small></article><article><p>价格监控 SKU</p><strong>127</strong><small>Amazon ASIN 已映射</small></article></div><div className="main-grid"><article className="panel"><div className="panel-head"><div><p className="kicker">OPERATING SIGNAL</p><h2>跨平台数据活跃度</h2></div></div><div className="chart">{trend.map((v,i)=><span key={i} style={{height:`${v}%`}}/>)}</div></article><article className="panel priority"><p className="kicker">NEXT PRIORITIES</p><h2>从上传后分析走向自动刷新</h2><ol><li><span>01</span><div><strong>接入 BBY / WMT API</strong><small>订单、退货、商品与价格</small></div><i>高</i></li><li><span>02</span><div><strong>确认完整 P&amp;L 口径</strong><small>成本、物流、佣金、退货处理</small></div><i>高</i></li><li><span>03</span><div><strong>迁移 SKU 清洗规则</strong><small>保留特殊映射与审计记录</small></div><i>中</i></li></ol></article></div><section className="module"><div className="section-head"><div><p className="kicker">FUNCTION MAP</p><h2>现有能力整合状态</h2></div></div>{modules.map((m,i)=><article className="module-row" key={m[1]} onClick={()=>setTab(Math.min(i+1,4))}><span>{m[0]}</span><div><strong>{m[1]}</strong><small>{m[2]}</small></div><span className="pill">{m[3]}</span><span className={i>1?"state warn":"state"}>{m[4]}</span></article>)}</section></>}

function Analysis({tab}:{tab:number}){const cfg=[null,["RETURNS INTELLIGENCE","退货率分析框架","Walmart 与 Best Buy 使用同一套时间、品牌、SKU 与退货原因筛选。",["累计退货率","月度趋势","退货原因","品牌 / SKU"]],["SALES & P&L","BBY 销售与贡献利润","订单、品牌、品类、售价与产品成本已可用；完整 P&L 还需物流和期间费用。",["销售额","销售件数","贡献利润","退货影响"]],["PRICE VERIFICATION","三平台价格核验","当前是浏览器自动抓取，不是官方 API；人工基准价来自 Price_reference。",["Amazon SKU","Walmart 实时价","Best Buy 实时价","价格异常"]],["DATA & AUTOMATION","数据来源与自动化状态","四套程序都已梳理；目前全部依赖人工提供 Excel 或网页抓取。",["BBY API","WMT API","价格 API","手工输入"]]][tab] as [string,string,string,string[]];return <section className="data-view"><div className="panel section-head"><div><p className="kicker">{cfg[0]}</p><h2>{cfg[1]}</h2><small>{cfg[2]}</small></div></div><div className="metric-grid">{cfg[3].map((x,i)=><article key={x}><p>0{i+1} · {x}</p><strong>{tab===4?"未接入":"—"}</strong></article>)}</div><div className="table"><p className="kicker">ANALYSIS PREVIEW</p><h2>分析结果</h2><div><b>对象</b><b>核心指标</b><b>数据口径</b><b>状态</b></div><div><span>{tab===1?"Walmart · 4P5H6AA":"数据模块"}</span><span>{tab===1?"13.90%":"—"}</span><span>现有 Excel</span><span>框架已就绪</span></div><div><span>{tab===1?"Best Buy · L10s Ultra":"下一期数据"}</span><span>待刷新</span><span>未接 API</span><span>等待接入</span></div></div></section>}
